//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEducatons
    {
        public int educationId { get; set; }
        public string department { get; set; }
        public string StartYear { get; set; }
        public string EndYear { get; set; }
        public string SchoolName { get; set; }
    }
}
